version: "3.1"

networks:
    api_network:
        driver: bridge

services:
    server:
        build: ./server
        image: "server"
        container_name: "rest_server"
        restart: on-failure
        depends_on:
            - redis
            - mongo
        ports:
            - "3000:3000"
        networks:
            - api_network
        environment:
            WAIT_HOSTS: mongo:27017

    redis:
        image: "redis"
        container_name: "redis"
        ports:
            - "6379:6379"
        networks:
            - api_network

    mongo:
        build: ./mongo
        image: "mongo"
        container_name: "mongo"
        volumes:
            - ./mongo/dbfiles:/data/db:rw
        ports:
            - "27017:27017"
        networks:
            - api_network
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 4rhQ9j
